repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: fix-encoding-pragma
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        files: ^api/
  - repo: https://github.com/ambv/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.10
        files: ^api/
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        name: bandit
        description: "Bandit is a tool for finding common security issues in Python code"
        exclude: ^updater/get_latest_release.py
        entry: bandit
        language: python
        language_version: python3
        types: [python]
        files: ^api/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^(src|public)/.*\.(ts|tsx|js|jsx|html|css)$
