version: "3"

networks:
  default-network: # docker network name, it will be <repo-name>_<default-network>
    driver: bridge

services:
  frontend:
    build: ./frontend
    ports:
        - "3000:3000"
    depends_on:
        - app
    networks:
      - default-network

  app:
    build: ./api
    ports:
        - "5000"
    networks:
      - default-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app # based on the name in line 12
      - frontend
    ports:
      - "80:80"
    networks:
      - default-network