version: "3"

services:
    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - app
    app:
        build:
            context: api
            dockerfile: Dockerfile
        ports:
            - "5000"
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app # based on the name in line 12
            - frontend
        ports:
            - "80:80"
