#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ "$(uname)" = "Darwin" ]; then
    npx lint-staged
elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
    npx lint-staged
elif [ "$(expr substr $(uname -s) 1 10)" = "MINGW32_NT" ]; then
    npx.cmd lint-staged
elif [ "$(expr substr $(uname -s) 1 10)" = "MINGW64_NT" ]; then
    npx.cmd lint-staged
fi